<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="camera_frame_length" value="0.01" />
    <xacro:property name="camera_frame_width" value="0.1" />
    <xacro:property name="camera_frame_height" value="0.05" />

    <link name="camera_frame_link">
        <visual>
            <geometry>
                <box size="${camera_frame_length} ${camera_frame_width} ${camera_frame_height}" />
            </geometry>
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <box size="${camera_frame_length} ${camera_frame_width} ${camera_frame_height}" />
            </geometry>
        </collision>
      <xacro:box_inertia m="0.1" l="${camera_frame_length}" w="${camera_frame_width}" h="${camera_frame_height}"
                           xyz="0 0 0" rpy="0 0 0" />
    </link>


    <joint name="base_camera_frame_joint" type="fixed">
        <parent link="base_link" />
        <child link="camera_frame_link" />
        <origin xyz="${(base_length + camera_frame_length) / 2.3} 0 ${(base_height / 2.0) + 0.5}" rpy="${pi/2} 0 0.25" />
    </joint>

    <link name="camera_link_optical">
    </link>

    <joint name="camera_optical_joint" type="fixed">
        <!-- these values have to be these values otherwise the gazebo camera
            image won't be aligned properly with the frame it is supposedly
            originating from -->
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2} "/>
        <parent link="camera_frame_link"/>
        <child link="camera_link_optical"/>
    </joint>


    <gazebo reference="camera_frame">  
        <sensor type="depth" name="camera">
            <always_on>true</always_on>
            <update_rate>30.0</update_rate>
            <camera>
                <horizontal_fov>1.0471975512</horizontal_fov>
                <image>
                <format>B8G8R8</format>
                <width>640</width>
                <height>480</height>
                </image>
                <clip>
                <near>0.05</near>
                <far>8.0</far>
                </clip>
            </camera>
            <plugin name="kinect_camera_controller" filename="libgazebo_ros_openni_kinect.so">
                <cameraName>camera</cameraName>
                <alwaysOn>true</alwaysOn>
                <updateRate>10</updateRate>
                <imageTopicName>rgb/image_raw</imageTopicName>
                <depthImageTopicName>depth/image_raw</depthImageTopicName>
                <pointCloudTopicName>depth/points</pointCloudTopicName>
                <cameraInfoTopicName>rgb/camera_info</cameraInfoTopicName>
                <depthImageCameraInfoTopicName>depth/camera_info</depthImageCameraInfoTopicName>
                <frameName>camera_frame</frameName>
                <baseline>0.1</baseline>
                <distortion_k1>0.0</distortion_k1>
                <distortion_k2>0.0</distortion_k2>
                <distortion_k3>0.0</distortion_k3>
                <distortion_t1>0.0</distortion_t1>
                <distortion_t2>0.0</distortion_t2>
                <pointCloudCutoff>0.4</pointCloudCutoff>
            </plugin>
        </sensor>
    </gazebo>
</robot>




