<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.8" />
    <xacro:property name="base_width" value="0.2" />
    <xacro:property name="base_height" value="0.4" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />
    <xacro:property name="imu_length" value="0.03" />
    <xacro:property name="imu_width" value="0.05" />
    <xacro:property name="imu_height" value="0.01" />

    <link name="base_footprint" />
     
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_length - 0.1}" rpy="0 0 0" />              
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
               <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_length - 0.1}" rpy="0 0 0" />
        </collision>
          <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}"
                           xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </link>

        <!-- IMU Link Definition -->
    <link name="imu_link">
        <visual>
            <geometry>
                <box size="${imu_length} ${imu_width} ${imu_height}" />
            </geometry>
            <origin xyz="0 0 ${imu_length - 0.1}" rpy="0 0 0" />              
            <material name="green" />
        </visual>
        <collision>
            <geometry>
               <box size="${imu_length} ${imu_width} ${imu_height}" />
            </geometry>
            <origin xyz="0 0 ${imu_length - 0.1}" rpy="0 0 0" />
          </collision>
          <xacro:box_inertia m="5.0" l="${2*imu_length}" w="${2*imu_width}" h="${2*imu_height}"
                           xyz="0 0 ${imu_height / 2.0}" rpy="0 0 0" />

    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${2*wheel_radius}" h="${2*wheel_length}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>


    <xacro:wheel_link prefix="right" />
    <xacro:wheel_link prefix="left" />
    <xacro:wheel_link prefix="right_rear" />
    <xacro:wheel_link prefix="left_rear" />

    

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${-base_length + 0.1}" rpy="0 0 0"/>
    </joint>


    <joint name="base_imu_joint" type="fixed">
        <parent link="base_link" />
        <child link="imu_link" />
        <origin xyz="0 0 0.8" rpy="0 0 0" />
    </joint>



    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="0.225 0.05 0.4775" rpy="${pi / 2.0} 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="0.225 ${wheel_length} 0.9225" rpy="${pi / 2.0} 0 0" />   ${wheel_length}
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_right_rear_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_rear_wheel_link" />
        <origin xyz="-0.225 0.05 0.4775" rpy="${pi / 2.0} 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_rear_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_rear_wheel_link" />
        <origin xyz="-0.225 0.05 0.9225" rpy="${pi / 2.0} 0 0" />
        <axis xyz="0 1 0" />
    </joint>
    


    <!-- <link name="hokuyo_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${2*wheel_radius}" h="${2*wheel_length}" 
                                xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
    </link>

    <joint name="base_hokuyo_joint" type="fixed">
        <parent link="base_link" />
        <child link="hokuyo_link" />
        <origin xyz="0.2 -0.15 0.7125" rpy="${pi / 2.0} 0 0" />
    </joint> -->
  
</robot>
